import ts from 'typescript';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const catalog = JSON.parse(readFileSync('src/data/catalog.json', 'utf8'));
const license = readFileSync('LICENSE', 'utf8');
const output = 'public/component-source';
// This folder is generated by this script and contains no authored files.
rmSync(output, { recursive: true, force: true });
mkdirSync(output, { recursive: true });
const manifest = { components: {}, files: {} };
const parsed = new Map();
function resolve(from, specifier) {
  const base = specifier.startsWith('@/') ? specifier.slice(2) : path.posix.join(path.posix.dirname(from), specifier);
  for (const suffix of ['', '.tsx', '.ts', '.json', '/index.tsx', '/index.ts']) {
    if (existsSync(base + suffix)) return base + suffix;
  }
  throw new Error(`Unresolved dependency ${specifier} in ${from}`);
}
function parse(file) {
  if (parsed.has(file)) return parsed.get(file);
  const content = readFileSync(file, 'utf8');
  const ast = ts.createSourceFile(file, content, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const imports = new Map();
  const dependencies = [];
  for (const statement of ast.statements) {
    if (!ts.isImportDeclaration(statement) || !ts.isStringLiteral(statement.moduleSpecifier)) continue;
    const specifier = statement.moduleSpecifier.text;
    if (!specifier.startsWith('.') && !specifier.startsWith('@/')) continue;
    const target = resolve(file, specifier);
    dependencies.push(target);
    const clause = statement.importClause;
    if (clause?.name) imports.set(clause.name.text, target);
    if (clause?.namedBindings && ts.isNamedImports(clause.namedBindings)) {
      for (const element of clause.namedBindings.elements) imports.set(element.name.text, target);
    }
  }
  const result = { content, ast, imports, dependencies };
  parsed.set(file, result);
  return result;
}
function mappings(file) {
  const { ast, imports } = parse(file);
  const mappings = new Map();
  function visit(node) {
    if (ts.isSwitchStatement(node)) {
      let ids = [];
      for (const clause of node.caseBlock.clauses) {
        if (ts.isCaseClause(clause) && ts.isStringLiteral(clause.expression)) ids.push(clause.expression.text);
        if (!clause.statements.length) continue;
        let component;
        function find(n) {
          if (!component && (ts.isJsxSelfClosingElement(n) || ts.isJsxOpeningElement(n)) && imports.has(n.tagName.getText(ast))) component = n.tagName.getText(ast);
          ts.forEachChild(n, find);
        }
        clause.statements.forEach(find);
        if (component) for (const id of ids) mappings.set(id, { file: imports.get(component), component });
        ids = [];
      }
    }
    ts.forEachChild(node, visit);
  }
  visit(ast);
  return mappings;
}
const previews = mappings('src/components/ComponentPreview.tsx');
const labs = mappings('src/components/LabPreview.tsx');
const loaderData = parse('src/data/loaders.ts');
const loaders = new Map();
function inspectLoader(node) {
  if (ts.isObjectLiteralExpression(node)) {
    const values = {};
    for (const p of node.properties) if (ts.isPropertyAssignment(p)) values[p.name.getText(loaderData.ast)] = p.initializer;
    if (values.kebabName && values.component) {
      const component = values.component.getText(loaderData.ast);
      loaders.set(values.kebabName.text, { file: loaderData.imports.get(component), component });
    }
  }
  ts.forEachChild(node, inspectLoader);
}
inspectLoader(loaderData.ast);
const aliases = { 'dither-area': 'dither-growth', 'dither-activity': 'activity-heatmap', 'dither-server': 'server-gauge', 'dither-traffic': 'traffic-bubble', 'dither-device': 'device-usage', 'dither-storage': 'storage-usage', 'dither-revenue': 'revenue-line', 'dither-uptime': 'uptime-chart' };
function publish(file, content) {
  if (manifest.files[file]) return;
  const text = /\.[jt]sx?$/.test(file) ? `/*\n${license.trim()}\n*/\n\n${content}` : content;
  const filename = createHash('sha256').update(text).digest('hex') + '.json';
  writeFileSync(path.join(output, filename), JSON.stringify(text));
  manifest.files[file] = filename;
}
function collect(file, seen = new Set()) {
  if (seen.has(file)) return seen;
  // Only publish explicit source dependencies, never environment or configuration secrets.
  if (!(file.startsWith('src/') || file.startsWith('registry/ui/')) || !/\.(tsx?|json)$/.test(file)) throw new Error(`Refusing source path: ${file}`);
  seen.add(file);
  const module = parse(file);
  publish(file, module.content);
  for (const dependency of module.dependencies) collect(dependency, seen);
  return seen;
}
for (const item of catalog) {
  let target;
  let props = 'theme="light"';
  let extra = '';
  let extraDependency;
  if (item.category === 'buttons') {
    target = { file: 'src/components/AnimatedButton.tsx', component: 'AnimatedButton' };
    extra = 'import { buttonsData } from "./data/buttons";\n';
    extraDependency = 'src/data/buttons.tsx';
    props += ` layoutMode="grid" config={{ ...buttonsData.find(item => item.id === "${item.id.slice(4)}")!, label: ${JSON.stringify(item.name)} }}`;
  } else if (item.category === 'text') {
    target = { file: 'src/components/text/AnimatedText.tsx', component: 'AnimatedText' };
    extra = 'import { textAnimationsData } from "./data/textAnimations";\n';
    extraDependency = 'src/data/textAnimations.ts';
    props += ` config={textAnimationsData.find(item => item.id === "${item.id}")!}`;
  } else if (item.category === 'loaders') { target = loaders.get(item.id); props = ''; }
  else if (item.category === 'lab') target = labs.get(item.id);
  else if (item.id === 'dither-book') target = { file: 'src/components/dither-charts/DitherBook.tsx', component: 'DitherBook' };
  else if (item.id.startsWith('mono-activity-')) {
    target = { file: 'src/components/mono-charts/MonoActivityHeatmap.tsx', component: 'MonoActivityHeatmap' };
    props += ` accentColor="${item.id.split('-').at(-1)}"`;
  } else target = previews.get(({ 'dither-heatmap': 'activity-heatmap', 'dither-gauge': 'server-gauge' })[item.id] || aliases[item.id] || item.id);
  if (!target?.file) throw new Error(`No source mapped for ${item.id}`);
  if (item.category === 'cards' && item.id !== 'dither-book') props = `hovered={true}${item.id.endsWith('-mono') ? ' isMonochrome={true}' : ''}`;
  const files = collect(target.file);
  if (extraDependency) collect(extraDependency, files);
  const examplePath = `examples/${item.id}/src/Example.tsx`;
  const importPath = './' + path.posix.relative('src', target.file).replace(/\.tsx?$/, '');
  publish(examplePath, `import React from "react";\nimport { ${target.component} } from ${JSON.stringify(importPath)};\n${extra}\nexport default function Example() {\n  return <${target.component} ${props} />;\n}\n`);
  manifest.components[item.id] = [examplePath, ...files, 'LICENSE'];
}
publish('LICENSE', license);
writeFileSync(path.join(output, 'manifest.json'), JSON.stringify(manifest));
console.log(`Prepared source and dependencies for ${catalog.length} components (${Object.keys(manifest.files).length} shared files).`);
